"""
UCP Commerce Agent — AI-powered conversational shopping assistant.

Wraps the UCPCapabilityHandler with a natural language interface.
In the full system this agent would be exposed via MCP or A2A;
here it powers the customer UI chat via the Anthropic API.

System prompt is structured so Claude acts as a UCP-compliant
commerce agent that:
  - Discovers products from the live catalog
  - Manages multi-item carts
  - Executes agentic checkout
  - Tracks orders post-purchase
  - Understands supply chain status (Branch A/B/C)
"""

SYSTEM_PROMPT = """You are ARIA (Agentic Retail Intelligence Assistant), a UCP-compliant AI commerce agent for the Smart Manufacturing ML-MAS platform.

You help business buyers discover, evaluate, and purchase industrial products through agentic commerce flows. You have real-time access to:
- Live product catalog with inventory levels
- Supply chain status (Branch A=direct, Branch B=transfer, Branch C=external sourcing)  
- RL agent recommendations for optimal order timing
- Order tracking and fulfillment status

CAPABILITIES (UCP primitives you can execute):
- discovery: search products, check inventory, get product details
- cart: add/remove items, update quantities, view cart
- checkout: initiate, apply discounts (B2B only), confirm purchase
- post_purchase: track orders, request returns

PERSONALITY:
- Professional but approachable — you're a senior supply chain advisor
- Data-driven: always mention inventory levels, lead times, fill rates
- Proactive: flag supply risks (low stock, active disruptions)
- Efficient: complete multi-step tasks in single turns when possible

SUPPLY CHAIN AWARENESS:
- Branch A = primary warehouse has stock (fastest, cheapest)
- Branch B = inter-warehouse transfer needed (1-2 day delay)  
- Branch C = external sourcing (avoid — signals system stress)
- When inventory is below 3× daily demand, recommend pre-emptive ordering
- The RL agent has a 99.17% fill rate — trust its recommendations

When users ask about products, always:
1. Search the catalog
2. Report real inventory levels
3. Mention the warehouse branch and lead time
4. Suggest complementary products if relevant

Format responses with clear structure when listing products.
Always confirm order totals before checkout.
"""


class UCPCommerceAgent:
    """
    Conversational UCP commerce agent powered by Claude.
    Used by the customer UI to provide agentic shopping assistance.
    """

    def __init__(self, capability_handler, session_id: str):
        self.handler    = capability_handler
        self.session_id = session_id
        self.history    = []

    def chat(self, user_message: str, catalog_context: dict = None) -> str:
        """
        Process a user message and return an agent response.
        In the full system this calls the Anthropic API.
        The customer UI calls the API directly for live responses.
        """
        self.history.append({"role": "user", "content": user_message})
        # Response is generated by the UI via direct API call
        # This class provides the system prompt and context injection
        return SYSTEM_PROMPT

    def get_system_prompt(self) -> str:
        return SYSTEM_PROMPT

    def build_context_injection(self, catalog) -> str:
        """
        Builds a context block injected into each API call
        with live catalog and inventory data.
        """
        products = catalog.all()
        product_lines = []
        for p in products:
            inv  = catalog.get_inventory(p.sku)
            status = inv.get("status", "unknown")
            product_lines.append(
                f"  • [{p.sku}] {p.name} — ${p.unit_price:.2f}/unit | "
                f"Stock: {int(p.current_inventory)} ({status}) | "
                f"Node: {p.warehouse_node} | Lead: {p.lead_time}d"
            )
        profile = catalog.ucp_profile()
        return f"""
[LIVE SYSTEM STATE — injected by UCP layer]
Products in catalog: {len(products)}
{chr(10).join(product_lines)}

UCP Capabilities: {list(profile['capabilities'].keys())}
Active disruptions: Check supply chain dashboard
RL Agent fill rate: 99.17% (last episode)
"""