"""
api/store_router.py — Store management endpoints.

Provides inventory views (read-only, managed by StoreInventoryAgent),
alert viewing, and staff listing for store managers.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session, joinedload
from typing import Optional

from db.database import get_db
from db.models import Store, StoreInventory, StockAlert, User
from auth.dependencies import get_current_user

router = APIRouter(prefix="/api/stores", tags=["stores"])


@router.get("")
def list_stores(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    List stores visible to the current user.
    - Store Manager / Sales Person: only their own store
    - Regional Manager: all stores in their region
    """
    if current_user.role == "regional_manager":
        stores = db.query(Store).filter(
            Store.region_id == current_user.region_id,
            Store.is_active == True,
        ).all()
    else:
        stores = db.query(Store).filter(
            Store.id == current_user.store_id,
            Store.is_active == True,
        ).all()

    result = []
    for store in stores:
        # Count inventory and staff
        inv_count = db.query(StoreInventory).filter(StoreInventory.store_id == store.id).count()
        staff_count = db.query(User).filter(User.store_id == store.id, User.is_active == True).count()
        total_stock = sum(
            inv.quantity for inv in
            db.query(StoreInventory).filter(StoreInventory.store_id == store.id).all()
        )
        active_alerts = db.query(StockAlert).filter(
            StockAlert.store_id == store.id,
            StockAlert.is_resolved == False,
        ).count()

        result.append({
            "id": store.id,
            "name": store.name,
            "store_code": store.store_code,
            "region_id": store.region_id,
            "products_tracked": inv_count,
            "staff_count": staff_count,
            "total_stock": round(total_stock, 1),
            "active_alerts": active_alerts,
        })

    return result


@router.get("/{store_id}")
def get_store(
    store_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Get detailed store information."""
    store = db.query(Store).filter(Store.id == store_id, Store.is_active == True).first()
    if not store:
        raise HTTPException(status_code=404, detail="Store not found")

    # Access check
    if current_user.role == "regional_manager":
        if store.region_id != current_user.region_id:
            raise HTTPException(status_code=403, detail="Store not in your region")
    elif current_user.store_id != store_id:
        raise HTTPException(status_code=403, detail="Access denied to this store")

    inventory = db.query(StoreInventory).options(
        joinedload(StoreInventory.product)
    ).filter(StoreInventory.store_id == store_id).all()

    total_stock = sum(inv.quantity for inv in inventory)
    alerts = db.query(StockAlert).filter(
        StockAlert.store_id == store_id,
        StockAlert.is_resolved == False,
    ).all()

    return {
        "id": store.id,
        "name": store.name,
        "store_code": store.store_code,
        "region_id": store.region_id,
        "total_stock": round(total_stock, 1),
        "inventory": [inv.to_dict() for inv in inventory],
        "active_alerts": [a.to_dict() for a in alerts],
    }


@router.get("/{store_id}/inventory")
def get_store_inventory(
    store_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Get full inventory for a store (read-only — managed by StoreInventoryAgent).
    """
    # Access check
    if current_user.role == "regional_manager":
        store = db.query(Store).filter(Store.id == store_id).first()
        if not store or store.region_id != current_user.region_id:
            raise HTTPException(status_code=403, detail="Access denied")
    elif current_user.store_id != store_id:
        raise HTTPException(status_code=403, detail="Access denied to this store")

    inventory = db.query(StoreInventory).options(
        joinedload(StoreInventory.product)
    ).filter(StoreInventory.store_id == store_id).all()

    return [inv.to_dict() for inv in inventory]


@router.get("/{store_id}/alerts")
def get_store_alerts(
    store_id: int,
    resolved: Optional[bool] = Query(None),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Get stock alerts for a store (auto-generated by StoreInventoryAgent)."""
    if current_user.role == "regional_manager":
        store = db.query(Store).filter(Store.id == store_id).first()
        if not store or store.region_id != current_user.region_id:
            raise HTTPException(status_code=403, detail="Access denied")
    elif current_user.store_id != store_id:
        raise HTTPException(status_code=403, detail="Access denied to this store")

    query = db.query(StockAlert).options(
        joinedload(StockAlert.product)
    ).filter(StockAlert.store_id == store_id)

    if resolved is not None:
        query = query.filter(StockAlert.is_resolved == resolved)

    alerts = query.order_by(StockAlert.created_at.desc()).limit(50).all()
    return [a.to_dict() for a in alerts]


@router.get("/{store_id}/staff")
def get_store_staff(
    store_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    List staff members for a store.
    Only store managers and regional managers can view staff.
    """
    if current_user.role not in ("store_manager", "regional_manager"):
        raise HTTPException(status_code=403, detail="Only managers can view staff")

    if current_user.role == "store_manager" and current_user.store_id != store_id:
        raise HTTPException(status_code=403, detail="Access denied to this store")

    if current_user.role == "regional_manager":
        store = db.query(Store).filter(Store.id == store_id).first()
        if not store or store.region_id != current_user.region_id:
            raise HTTPException(status_code=403, detail="Access denied")

    staff = db.query(User).filter(
        User.store_id == store_id,
        User.is_active == True,
    ).all()

    return [u.to_dict() for u in staff]
